services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  producer:
    build:
      context: ./data_source
      dockerfile: Dockerfile
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_USER: ${KAFKA_USER}
      KAFKA_PWD: ${KAFKA_PWD}      
      SASL_MECHANISM: ${SASL_MECHANISM}      
      SECURITY_PROTOCOL: ${SECURITY_PROTOCOL}     
    depends_on:
      - kafka

  backend:
    build:
      context: ./backend/app
    environment:
      PORT: 8000
      KAFKA_HOST: kafka:9092
      KAFKA_USER: ${KAFKA_USER}
      KAFKA_PWD: ${KAFKA_PWD}      
      SASL_MECHANISM: ${SASL_MECHANISM}      
      SECURITY_PROTOCOL: ${SECURITY_PROTOCOL}        
    volumes:
      - /Users/tiziano/Documents/aicemy/model:/app/model  # Mount the model directory
    depends_on:
      - kafka
      - producer
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
